pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'keymapviewer'

include 'common'
include 'versions:mc2612'
include 'versions:mc262'
include 'versions:mc1217'
include 'versions:mc121'
include 'versions:mc1201'